image: Visual Studio 2022
version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\*.*nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/radek41-3uj048yghh6h
  api_key:
    secure: N4Ceb4PGYD3hKN+N2ZkaXtocmrZeUb4jBrFLr/tvSzc=
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  server: https://ci.appveyor.com/nuget/radek41-3uj048yghh6h
  api_key:
    secure: N4Ceb4PGYD3hKN+N2ZkaXtocmrZeUb4jBrFLr/tvSzc=
  skip_symbols: true
  on:
    branch: develop
- provider: NuGet
  name: production
  api_key:
    secure: ma6VOuNBMjh9UUtr2LvxSnLepmxr855/6U4/bMT/oqgEgol1yCQVrh1VWw4NLIPW
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  auth_token:
    secure: 5obJpl3w5Trw5/FpDqp15U+qxbAC5AztY0k3F8hjsZ3wecH0tX0qc66LA/HVxCSNnHf5NarxmkS0xr6952ByAmiwPDPcBJPF98xtkg5pdnMOhhken8Ux/oekK/sQzf2g
  artifact: /.*\.*nupkg/
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
