image: Visual Studio 2022
version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\*.*nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/radek41-3uj048yghh6h
  api_key:
    secure: N4Ceb4PGYD3hKN+N2ZkaXtocmrZeUb4jBrFLr/tvSzc=
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  server: https://ci.appveyor.com/nuget/radek41-3uj048yghh6h
  api_key:
    secure: N4Ceb4PGYD3hKN+N2ZkaXtocmrZeUb4jBrFLr/tvSzc=
  skip_symbols: true
  on:
    branch: develop
- provider: NuGet
  name: production
  api_key:
    secure: EWYOXnkIXZb8l2dTfNhXJ0Y5dLZV7u/P+CUr+F3RM2TXNR+bJEj6/hp2Pton6Vgh
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG)
  description: 'Release description'
  auth_token:
    secure: 5obJpl3w5Trw5/FpDqp15TeYW0vOTxCI/tnIBWOVhiwGjJk2IDETwNCjqXtWvr9OrgAS7LGZfFQLf28QA/P/n44Dvyw95OznBvPXEwXSR9ncFd3jYEoKvpYhX7HZHIMl
  artifact: /.*\.*nupkg/
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
